server:
  port: 83
spring:
  redis:
    host: 192.168.1.129
    port: 6379
    password: pamirs@2020
  datasource:
    web:
      username: root
      password: shulie@2020
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.129:3306/trodb_combine_225?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    cloud:
      username: root
      password: shulie@2020
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.129:3306/crank?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    amdb:
      username: root
      password: shulie@2020
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.129:3306/amdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
config:
  clickhouse:
    url: jdbc:clickhouse://192.168.1.129:8123,192.168.1.129:8123/default
    userName: default
    password: rU4zGjA/
    enableRound: true
    batchCount: 100
performance:
  base:
    agent:
      frequency: 1
