apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-receiver
  namespace: shulie-takin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-receiver
  template:
    metadata:
      labels:
        app: kafka-receiver
    spec:
      containers:
      - name: kafka-receiver
        image: harbor.dcos.xixian.unicom.local/skyeye-platform-xx-pbc/stresstest/kafka-receiver:2.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 4G
          limits:
            memory: 4G
        command: ["./start.sh"]

