FROM 10.172.49.246/skyeye-platform/stresstest/base:1.0.0
WORKDIR /data/apps/takin-surge
COPY doc/deploy.properties /data/apps/takin-surge/deploy.properties
COPY surge-deploy-pradar-kafka/target/*.jar /data/apps/takin-surge/takin-surge.jar
